name: Upload Node.js 10 and 12 tool cache
on:
  workflow_dispatch:
jobs:
  upload_tool_cache:
    runs-on: macos-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Include azure/login@v1 dependency
        uses: azure/login@v1
      - name: Include azure/webapps-deploy@v2 dependency
        uses: azure/webapps-deploy@v2
      - name: Setup Node 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
